/* Generated by scripts/development/generate_openapi_types.py */
/* Run uv run python scripts/development/generate_openapi_types.py to update */

export interface components {
  "schemas": {
    "AgentType": "explorer" | "analyst" | "reviewer";
    "AssetGrantResponse": {
      "column_name": (string | null);
      "created_at": string;
      "data_source": string;
      "database_name": (string | null);
      "id": string;
      "role": string;
      "scope": string;
      "table_name": (string | null);
    };
    "Attachment": {
      "description"?: (string | null);
      "f_path": string;
      "media_type"?: (string | null);
    };
    "AttachmentReference": {
      "f_path": string;
    };
    "Body_api_upload_attachment_api_v1_chat_attachment_upload_post": {
      "conversation_id": string;
      "file": string;
    };
    "Body_import_metadata_api_v1_meta_import_post": {
      "file": string;
    };
    "ChangePasswordRequest": {
      "current_password": string;
      "new_password": string;
    };
    "ChatStreamDoneEvent": {
      "type": "done";
    };
    "ChatStreamErrorEvent": {
      "content": string;
      "type": "error";
    };
    "ChatStreamEvent": (components["schemas"]["ChatStreamMessageEvent"] | components["schemas"]["ChatStreamThinkingEvent"] | components["schemas"]["ChatStreamMessageDeltaEvent"] | components["schemas"]["ChatStreamErrorEvent"] | components["schemas"]["ChatStreamDoneEvent"] | components["schemas"]["ChatStreamSubagentMessageEvent"] | components["schemas"]["ChatStreamSubagentThinkingEvent"] | components["schemas"]["ChatStreamSubagentMessageDeltaEvent"] | components["schemas"]["ChatStreamSubagentStatusEvent"]);
    "ChatStreamMessageDeltaEvent": {
      "delta": string;
      "message_id": string;
      "reset"?: boolean;
      "type": "message_delta";
    };
    "ChatStreamMessageEvent": {
      "message": components["schemas"]["MessageResponse"];
      "type": "message";
    };
    "ChatStreamRequest": {
      "conversation_id": string;
      "message": components["schemas"]["UserMessageRequest"];
    };
    "ChatStreamSubagentMessageDeltaEvent": {
      "agent_type": components["schemas"]["AgentType"];
      "analysis_id": string;
      "delegation_id": string;
      "delta": string;
      "instruction"?: (string | null);
      "message_id": string;
      "parent_tool_call_id"?: (string | null);
      "reset"?: boolean;
      "session_id": string;
      "type": "subagent_message_delta";
    };
    "ChatStreamSubagentMessageEvent": {
      "agent_type": components["schemas"]["AgentType"];
      "analysis_id": string;
      "delegation_id": string;
      "instruction"?: (string | null);
      "message": components["schemas"]["MessageResponse"];
      "parent_tool_call_id"?: (string | null);
      "session_id": string;
      "type": "subagent_message";
    };
    "ChatStreamSubagentStatusEvent": {
      "agent_type": components["schemas"]["AgentType"];
      "analysis_id": string;
      "delegation_id": string;
      "instruction"?: (string | null);
      "parent_tool_call_id"?: (string | null);
      "session_id": string;
      "status": "running" | "completed" | "needs_repair" | "failed" | "cancelled";
      "type": "subagent_status";
    };
    "ChatStreamSubagentThinkingEvent": {
      "agent_type": components["schemas"]["AgentType"];
      "analysis_id": string;
      "delegation_id": string;
      "delta": string;
      "instruction"?: (string | null);
      "message_id": string;
      "parent_tool_call_id"?: (string | null);
      "reset"?: boolean;
      "session_id": string;
      "type": "subagent_thinking";
    };
    "ChatStreamThinkingEvent": {
      "delta": string;
      "message_id": string;
      "reset"?: boolean;
      "type": "thinking";
    };
    "ColumnBatchDeleteRequest": {
      "columns": Array<components["schemas"]["ColumnReference"]>;
    };
    "ColumnIndexSyncRequest": {
      "columns": Array<components["schemas"]["ColumnReference"]>;
    };
    "ColumnInfoRequest": {
      "alias"?: Array<string>;
      "description": string;
      "index_values": boolean;
      "reference_c_name"?: (string | null);
      "reference_t_name"?: (string | null);
    };
    "ColumnInfoResponse": {
      "alias": Array<string>;
      "description": string;
      "examples": Array<unknown>;
      "index_values": boolean;
      "index_version": number;
      "meta_version": number;
      "name": string;
      "reference_c_name": (string | null);
      "reference_t_name": (string | null);
      "t_name": string;
      "type": string;
      "value_index_state": (components["schemas"]["ValueIndexSyncStateResponse"] | null);
    };
    "ColumnReference": {
      "c_name": string;
      "t_name": string;
    };
    "ColumnValueIndexSyncRequest": {
      "columns": Array<components["schemas"]["ColumnReference"]>;
      "mode": "full" | "incremental";
    };
    "ConversationListResponse": {
      "conversations": Array<components["schemas"]["ConversationResponse"]>;
    };
    "ConversationResponse": {
      "conversation_id": string;
      "running": boolean;
      "title": string;
      "update_at": string;
    };
    "ConversationRunStatusResponse": {
      "running": boolean;
    };
    "CreateConversationRequest": {
      "initial_message"?: (string | null);
      "is_draft"?: boolean;
    };
    "CreateDorisRoleRequest": {
      "description": string;
      "query_user": string;
      "role": string;
      "workload_group": string;
    };
    "CreateUserRequest": {
      "doris_role"?: (string | null);
      "email": string;
      "is_admin"?: boolean;
      "password": string;
      "username": string;
    };
    "DeleteAttachmentRequest": {
      "conversation_id": string;
      "f_path": string;
    };
    "DeleteConversationRequest": {
      "conversation_ids": Array<string>;
    };
    "DorisExistingRoleResponse": {
      "doris_users": Array<string>;
      "managed": boolean;
      "name": string;
    };
    "DorisRoleResponse": {
      "description": string;
      "doris_grants": ({
        [key: string]: unknown;
      } | null);
      "exists_in_doris": boolean;
      "is_default": boolean;
      "name": string;
      "query_user": string;
      "workload_group": string;
    };
    "DropRowPolicyRequest": {
      "policy_name": string;
      "table_name": string;
    };
    "EvalDelegationResponse": {
      "agent_type": components["schemas"]["AgentType"];
      "analysis_id": string;
      "attachments"?: (Array<components["schemas"]["Attachment"]> | null);
      "delegation_id": string;
      "message": string;
      "result"?: ({
        [key: string]: unknown;
      } | null);
      "session_id": string;
    };
    "ImageContent": {
      "image_url": string;
      "type": "image_url";
    };
    "ImportMode": "merge" | "replace";
    "LoginRequest": {
      "identifier": string;
      "password": string;
    };
    "LogoutRequest": {
      "refresh_token": string;
    };
    "MessageListResponse": {
      "messages": Array<components["schemas"]["MessageResponse"]>;
    };
    "MessageResponse": {
      "attachments"?: (Array<components["schemas"]["Attachment"]> | null);
      "created_at"?: (string | null);
      "eval_delegations"?: (Array<components["schemas"]["EvalDelegationResponse"]> | null);
      "finish_reason"?: (string | null);
      "message_id"?: (string | null);
      "parts": Array<(components["schemas"]["TextContent"] | components["schemas"]["ImageContent"] | components["schemas"]["ThinkingContent"] | components["schemas"]["ToolCallPart"] | components["schemas"]["ToolResultPart"])>;
      "role": "user" | "assistant" | "tool" | "system";
    };
    "MetaImportResponse": {
      "columns": components["schemas"]["ResourceImportChanges"];
      "dry_run": boolean;
      "metrics": components["schemas"]["ResourceImportChanges"];
      "mode": string;
      "tables": components["schemas"]["ResourceImportChanges"];
    };
    "MetricBatchDeleteRequest": {
      "metrics": Array<string>;
    };
    "MetricIndexSyncRequest": {
      "metrics": Array<string>;
    };
    "MetricInfoRequest": {
      "alias"?: Array<string>;
      "description": string;
      "relevant_columns"?: Array<components["schemas"]["ColumnReference"]>;
    };
    "MetricInfoResponse": {
      "alias": Array<string>;
      "description": string;
      "index_version": number;
      "meta_version": number;
      "name": string;
      "relevant_columns": Array<components["schemas"]["ColumnReference"]>;
    };
    "ProblemDetails": {
      "detail"?: (string | null);
      "instance"?: (string | null);
      "status": number;
      "title": string;
      "type": string;
      [key: string]: unknown;
    };
    "QueryExperienceAssetResponse": {
      "column": (string | null);
      "database": string;
      "kind": "table" | "column";
      "table": string;
    };
    "QueryExperienceBatchRequest": {
      "experience_ids": Array<string>;
    };
    "QueryExperienceDeletionResponse": {
      "deletion_requested_at": string;
      "id": string;
      "status"?: "deleting";
    };
    "QueryExperienceDetailResponse": {
      "asset_count": number;
      "assets": Array<components["schemas"]["QueryExperienceAssetResponse"]>;
      "created_at": string;
      "deletion_requested_at": (string | null);
      "deletion_requested_by_user_id": (number | null);
      "disabled_at": (string | null);
      "disabled_by_user_id": (number | null);
      "disabled_reason": (components["schemas"]["QueryExperienceDisabledReason"] | null);
      "execution_count": number;
      "fingerprint": string;
      "id": string;
      "index_status": "synced" | "pending";
      "last_executed_at": (string | null);
      "latest_purpose": string;
      "purpose_count": number;
      "purposes": Array<string>;
      "role_name": string;
      "sql_template": string;
      "sql_template_preview": string;
      "status": components["schemas"]["QueryExperienceStatus"];
      "updated_at": string;
    };
    "QueryExperienceDisabledReason": "metadata_changed" | "admin";
    "QueryExperienceListResponse": {
      "has_more": boolean;
      "items": Array<components["schemas"]["QueryExperienceOverviewResponse"]>;
      "limit": number;
      "offset": number;
      "total": number;
    };
    "QueryExperienceOverviewResponse": {
      "asset_count": number;
      "created_at": string;
      "disabled_reason": (components["schemas"]["QueryExperienceDisabledReason"] | null);
      "execution_count": number;
      "id": string;
      "index_status": "synced" | "pending";
      "last_executed_at": (string | null);
      "latest_purpose": string;
      "purpose_count": number;
      "role_name": string;
      "sql_template_preview": string;
      "status": components["schemas"]["QueryExperienceStatus"];
      "updated_at": string;
    };
    "QueryExperienceSourceExecutionListResponse": {
      "has_more": boolean;
      "items": Array<components["schemas"]["QueryExperienceSourceExecutionResponse"]>;
      "limit": number;
      "offset": number;
      "total": number;
    };
    "QueryExperienceSourceExecutionResponse": {
      "analysis_id": string;
      "created_at": string;
      "id": string;
      "purpose": string;
      "row_count": (number | null);
      "session_id": string;
      "user_id": number;
    };
    "QueryExperienceStatus": "active" | "disabled" | "deleting";
    "RefreshRequest": {
      "refresh_token": string;
    };
    "ResourceImportChanges": {
      "created_count": number;
      "created_keys": Array<string>;
      "deleted_count": number;
      "deleted_keys": Array<string>;
      "updated_count": number;
      "updated_keys": Array<string>;
    };
    "RowPolicyRequest": {
      "policy_name": string;
      "policy_type"?: "RESTRICTIVE" | "PERMISSIVE";
      "predicate": string;
      "table_name": string;
    };
    "RowPolicyResponse": {
      "catalog_name": string;
      "database_name": string;
      "policy_name": string;
      "policy_type": "RESTRICTIVE" | "PERMISSIVE";
      "predicate": string;
      "table_name": string;
    };
    "SelectGrantRequest": {
      "columns"?: Array<string>;
      "table_name"?: (string | null);
    };
    "SemanticIndexUpsertResponse": {
      "semantic_index_task_id": (string | null);
    };
    "SubagentMessageListResponse": {
      "messages": Array<components["schemas"]["MessageResponse"]>;
      "status": "running" | "completed" | "needs_repair" | "failed" | "cancelled";
    };
    "TableBatchDeleteRequest": {
      "tables": Array<string>;
    };
    "TableIndexSyncRequest": {
      "tables": Array<string>;
    };
    "TableInfoRequest": {
      "description": string;
      "role": "fact" | "dim";
      "value_index_cursor_column"?: (string | null);
    };
    "TableInfoResponse": {
      "description": string;
      "meta_version": number;
      "name": string;
      "primary_key_columns": Array<string>;
      "role": "fact" | "dim";
      "value_index_cursor_column": (string | null);
    };
    "TableValueIndexSyncRequest": {
      "mode": "full" | "incremental";
      "tables": Array<string>;
    };
    "TaskAcceptedResponse": {
      "task_id": string;
    };
    "TaskStatusResponse": {
      "error"?: (string | null);
      "ready": boolean;
      "result"?: (unknown | null);
      "state": string;
      "successful": (boolean | null);
      "task_id": string;
    };
    "TextContent": {
      "text": string;
      "type": "text";
    };
    "ThinkingContent": {
      "status"?: "streaming" | "complete" | "interrupted";
      "text": string;
      "type": "thinking";
    };
    "TokenResponse": {
      "access_token": string;
      "expires_in": number;
      "refresh_expires_in": number;
      "refresh_token": string;
      "token_type"?: string;
      "user": components["schemas"]["UserResponse"];
    };
    "ToolCallPart": {
      "args"?: {
        [key: string]: unknown;
      };
      "name": string;
      "tool_call_id": string;
      "type": "tool_call";
    };
    "ToolResultPart": {
      "content": string;
      "name": string;
      "tool_call_id": string;
      "type": "tool_result";
    };
    "UpdateConversationRequest": {
      "conversation_id": string;
      "title": string;
    };
    "UpdateUserRequest": {
      "doris_role"?: (string | null);
      "email"?: (string | null);
      "is_admin"?: (boolean | null);
      "password"?: (string | null);
      "username"?: (string | null);
    };
    "UploadAttachmentResponse": {
      "attachment": components["schemas"]["Attachment"];
    };
    "UserListResponse": {
      "has_more": boolean;
      "limit": number;
      "offset": number;
      "total": number;
      "users": Array<components["schemas"]["UserResponse"]>;
    };
    "UserMessageRequest": {
      "attachments"?: (Array<components["schemas"]["AttachmentReference"]> | null);
      "parts": Array<(components["schemas"]["TextContent"] | components["schemas"]["ImageContent"])>;
    };
    "UserResponse": {
      "created_at": string;
      "doris_role": (string | null);
      "email": string;
      "id": number;
      "is_active": boolean;
      "is_admin": boolean;
      "username": string;
    };
    "ValueIndexSyncStateResponse": {
      "current_generation": (string | null);
      "cursor_value": ({
        [key: string]: unknown;
      } | null);
      "last_error": (string | null);
      "last_full_synced_at": (string | null);
      "last_incremental_synced_at": (string | null);
      "last_sync_mode": ("full" | "incremental" | null);
      "last_synced_at": (string | null);
      "status": "syncing" | "succeeded" | "failed";
      "updated_at": string;
    };
  };
}

export interface operations {
  "api_create_conversation_api_v1_chat_create_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["CreateConversationRequest"];
    };
    "responses": {
      "201": {
        "content": {
        "application/json": components["schemas"]["ConversationResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_delete_attachment_api_v1_chat_attachment_delete_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["DeleteAttachmentRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": unknown;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_delete_conversations_api_v1_chat_delete_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["DeleteConversationRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": unknown;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_delete_draft_conversation_api_v1_chat_draft__conversation_id__delete": {
    "parameters": {
      "path": {
        "conversation_id": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "204": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_get_attachment_api_v1_chat_attachment_get_get": {
    "parameters": {
      "path"?: never;
      "query": {
        "conversation_id": string;
        "f_path": string;
      };
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": unknown;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_get_conversation_run_status_api_v1_chat__conversation_id__run_get": {
    "parameters": {
      "path": {
        "conversation_id": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["ConversationRunStatusResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_get_conversations_api_v1_chat_ls_get": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["ConversationListResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_get_messages_api_v1_chat_ls__conversation_id__get": {
    "parameters": {
      "path": {
        "conversation_id": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["MessageListResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_get_subagent_messages_api_v1_chat__conversation_id__subagents__analysis_id___agent_type___session_id__runs__delegation_id__messages_get": {
    "parameters": {
      "path": {
        "agent_type": "explorer" | "analyst" | "reviewer";
        "analysis_id": string;
        "conversation_id": string;
        "delegation_id": string;
        "session_id": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["SubagentMessageListResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_resume_chat_api_v1_chat__conversation_id__resume_post": {
    "parameters": {
      "path": {
        "conversation_id": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_stop_conversation_run_api_v1_chat__conversation_id__stop_post": {
    "parameters": {
      "path": {
        "conversation_id": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "204": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_stream_chat_api_v1_chat_stream_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["ChatStreamRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["ChatStreamEvent"];
        "text/event-stream": components["schemas"]["ChatStreamEvent"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_subscribe_conversation_run_api_v1_chat__conversation_id__events_get": {
    "parameters": {
      "path": {
        "conversation_id": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_update_conversation_api_v1_chat_update_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["UpdateConversationRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": unknown;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_upload_attachment_api_v1_chat_attachment_upload_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "multipart/form-data": components["schemas"]["Body_api_upload_attachment_api_v1_chat_attachment_upload_post"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["UploadAttachmentResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "change_password_api_v1_auth_change_password_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["ChangePasswordRequest"];
    };
    "responses": {
      "204": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "clear_default_doris_role_api_v1_admin_doris_roles_default_delete": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "204": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "create_doris_role_api_v1_admin_doris_roles_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["CreateDorisRoleRequest"];
    };
    "responses": {
      "201": {
        "content": {
        "application/json": components["schemas"]["DorisRoleResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "create_row_policy_api_v1_admin_doris_roles__role__row_policies_post": {
    "parameters": {
      "path": {
        "role": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["RowPolicyRequest"];
    };
    "responses": {
      "201": {
        "content": {
        "application/json": unknown;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "create_user_api_v1_admin_users_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["CreateUserRequest"];
    };
    "responses": {
      "201": {
        "content": {
        "application/json": components["schemas"]["UserResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "delete_columns_api_v1_meta_columns_batch_delete_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["ColumnBatchDeleteRequest"];
    };
    "responses": {
      "204": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "delete_doris_role_api_v1_admin_doris_roles__role__delete": {
    "parameters": {
      "path": {
        "role": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "204": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "delete_metrics_api_v1_meta_metrics_batch_delete_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["MetricBatchDeleteRequest"];
    };
    "responses": {
      "204": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "delete_query_experience_api_v1_admin_query_experiences__experience_id__delete": {
    "parameters": {
      "path": {
        "experience_id": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "202": {
        "content": {
        "application/json": components["schemas"]["QueryExperienceDeletionResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "delete_query_experiences_api_v1_admin_query_experiences_batch_delete_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["QueryExperienceBatchRequest"];
    };
    "responses": {
      "204": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "delete_tables_api_v1_meta_tables_batch_delete_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["TableBatchDeleteRequest"];
    };
    "responses": {
      "204": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "delete_user_api_v1_admin_users__user_id__delete": {
    "parameters": {
      "path": {
        "user_id": number;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "204": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "disable_query_experience_api_v1_admin_query_experiences__experience_id__disable_post": {
    "parameters": {
      "path": {
        "experience_id": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["QueryExperienceDetailResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "disable_query_experiences_api_v1_admin_query_experiences_batch_disable_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["QueryExperienceBatchRequest"];
    };
    "responses": {
      "204": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "drop_row_policy_api_v1_admin_doris_roles__role__row_policies_delete": {
    "parameters": {
      "path": {
        "role": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["DropRowPolicyRequest"];
    };
    "responses": {
      "204": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "export_metadata_api_v1_meta_export_get": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "get_query_experience_api_v1_admin_query_experiences__experience_id__get": {
    "parameters": {
      "path": {
        "experience_id": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["QueryExperienceDetailResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "get_task_status_api_v1_tasks__task_id__get": {
    "parameters": {
      "path": {
        "task_id": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["TaskStatusResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "grant_select_api_v1_admin_doris_roles__role__select_grants_post": {
    "parameters": {
      "path": {
        "role": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["SelectGrantRequest"];
    };
    "responses": {
      "201": {
        "content": {
        "application/json": Array<components["schemas"]["AssetGrantResponse"]>;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "import_metadata_api_v1_meta_import_post": {
    "parameters": {
      "path"?: never;
      "query": {
        "dry_run"?: boolean;
        "mode"?: components["schemas"]["ImportMode"];
      };
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "multipart/form-data": components["schemas"]["Body_import_metadata_api_v1_meta_import_post"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": (components["schemas"]["MetaImportResponse"] | components["schemas"]["TaskAcceptedResponse"]);
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "list_column_infos_api_v1_meta_tables__t_name__columns_get": {
    "parameters": {
      "path": {
        "t_name": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": Array<components["schemas"]["ColumnInfoResponse"]>;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "list_doris_roles_api_v1_admin_doris_roles_get": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": Array<components["schemas"]["DorisRoleResponse"]>;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "list_doris_workload_groups_api_v1_admin_doris_roles_workload_groups_get": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": Array<string>;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "list_existing_doris_roles_api_v1_admin_doris_roles_existing_get": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": Array<components["schemas"]["DorisExistingRoleResponse"]>;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "list_metric_infos_api_v1_meta_metrics_get": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": Array<components["schemas"]["MetricInfoResponse"]>;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "list_query_experience_source_executions_api_v1_admin_query_experiences__experience_id__executions_get": {
    "parameters": {
      "path": {
        "experience_id": string;
      };
      "query": {
        "limit"?: number;
        "offset"?: number;
      };
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["QueryExperienceSourceExecutionListResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "list_query_experiences_api_v1_admin_query_experiences_get": {
    "parameters": {
      "path"?: never;
      "query": {
        "limit"?: number;
        "offset"?: number;
        "query"?: (string | null);
        "role_name"?: (string | null);
        "status"?: ("active" | "disabled" | "deleting" | null);
      };
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["QueryExperienceListResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "list_row_policies_api_v1_admin_doris_roles__role__row_policies_get": {
    "parameters": {
      "path": {
        "role": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": Array<components["schemas"]["RowPolicyResponse"]>;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "list_select_grants_api_v1_admin_doris_roles__role__select_grants_get": {
    "parameters": {
      "path": {
        "role": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": Array<components["schemas"]["AssetGrantResponse"]>;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "list_source_tables_api_v1_meta_source_tables_get": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": Array<string>;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "list_table_infos_api_v1_meta_tables_get": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": Array<components["schemas"]["TableInfoResponse"]>;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "list_users_api_v1_admin_users_get": {
    "parameters": {
      "path"?: never;
      "query": {
        "limit"?: number;
        "offset"?: number;
        "query"?: (string | null);
      };
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["UserListResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "login_api_v1_auth_login_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["LoginRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["TokenResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "logout_api_v1_auth_logout_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["LogoutRequest"];
    };
    "responses": {
      "204": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "me_api_v1_auth_me_get": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["UserResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "refresh_api_v1_auth_refresh_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["RefreshRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["TokenResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "revoke_all_select_api_v1_admin_doris_roles__role__select_grants_all_delete": {
    "parameters": {
      "path": {
        "role": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "204": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "revoke_select_api_v1_admin_doris_roles__role__select_grants_delete": {
    "parameters": {
      "path": {
        "role": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["SelectGrantRequest"];
    };
    "responses": {
      "204": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "set_default_doris_role_api_v1_admin_doris_roles__role__default_put": {
    "parameters": {
      "path": {
        "role": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["DorisRoleResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "sync_column_indexes_api_v1_meta_columns_sync_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["ColumnIndexSyncRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["TaskAcceptedResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "sync_column_values_api_v1_meta_columns_sync_values_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["ColumnValueIndexSyncRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["TaskAcceptedResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "sync_metric_indexes_api_v1_meta_metrics_sync_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["MetricIndexSyncRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["TaskAcceptedResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "sync_table_indexes_api_v1_meta_tables_sync_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["TableIndexSyncRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["TaskAcceptedResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "sync_table_values_api_v1_meta_tables_sync_values_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["TableValueIndexSyncRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["TaskAcceptedResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "update_user_api_v1_admin_users__user_id__put": {
    "parameters": {
      "path": {
        "user_id": number;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["UpdateUserRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["UserResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "upsert_column_info_api_v1_meta_tables__t_name__columns__c_name__put": {
    "parameters": {
      "path": {
        "c_name": string;
        "t_name": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["ColumnInfoRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["SemanticIndexUpsertResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "upsert_metric_info_api_v1_meta_metrics__metric_name__put": {
    "parameters": {
      "path": {
        "metric_name": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["MetricInfoRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["SemanticIndexUpsertResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "upsert_table_info_api_v1_meta_tables__t_name__put": {
    "parameters": {
      "path": {
        "t_name": string;
      };
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["TableInfoRequest"];
    };
    "responses": {
      "204": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
}

export interface paths {
  "/api/v1/admin/doris-roles": {
    "get": operations["list_doris_roles_api_v1_admin_doris_roles_get"];
    "post": operations["create_doris_role_api_v1_admin_doris_roles_post"];
  };
  "/api/v1/admin/doris-roles/default": {
    "delete": operations["clear_default_doris_role_api_v1_admin_doris_roles_default_delete"];
  };
  "/api/v1/admin/doris-roles/existing": {
    "get": operations["list_existing_doris_roles_api_v1_admin_doris_roles_existing_get"];
  };
  "/api/v1/admin/doris-roles/workload-groups": {
    "get": operations["list_doris_workload_groups_api_v1_admin_doris_roles_workload_groups_get"];
  };
  "/api/v1/admin/doris-roles/{role}": {
    "delete": operations["delete_doris_role_api_v1_admin_doris_roles__role__delete"];
  };
  "/api/v1/admin/doris-roles/{role}/default": {
    "put": operations["set_default_doris_role_api_v1_admin_doris_roles__role__default_put"];
  };
  "/api/v1/admin/doris-roles/{role}/row-policies": {
    "get": operations["list_row_policies_api_v1_admin_doris_roles__role__row_policies_get"];
    "post": operations["create_row_policy_api_v1_admin_doris_roles__role__row_policies_post"];
    "delete": operations["drop_row_policy_api_v1_admin_doris_roles__role__row_policies_delete"];
  };
  "/api/v1/admin/doris-roles/{role}/select-grants": {
    "get": operations["list_select_grants_api_v1_admin_doris_roles__role__select_grants_get"];
    "post": operations["grant_select_api_v1_admin_doris_roles__role__select_grants_post"];
    "delete": operations["revoke_select_api_v1_admin_doris_roles__role__select_grants_delete"];
  };
  "/api/v1/admin/doris-roles/{role}/select-grants/all": {
    "delete": operations["revoke_all_select_api_v1_admin_doris_roles__role__select_grants_all_delete"];
  };
  "/api/v1/admin/query-experiences": {
    "get": operations["list_query_experiences_api_v1_admin_query_experiences_get"];
  };
  "/api/v1/admin/query-experiences/batch-delete": {
    "post": operations["delete_query_experiences_api_v1_admin_query_experiences_batch_delete_post"];
  };
  "/api/v1/admin/query-experiences/batch-disable": {
    "post": operations["disable_query_experiences_api_v1_admin_query_experiences_batch_disable_post"];
  };
  "/api/v1/admin/query-experiences/{experience_id}": {
    "get": operations["get_query_experience_api_v1_admin_query_experiences__experience_id__get"];
    "delete": operations["delete_query_experience_api_v1_admin_query_experiences__experience_id__delete"];
  };
  "/api/v1/admin/query-experiences/{experience_id}/disable": {
    "post": operations["disable_query_experience_api_v1_admin_query_experiences__experience_id__disable_post"];
  };
  "/api/v1/admin/query-experiences/{experience_id}/executions": {
    "get": operations["list_query_experience_source_executions_api_v1_admin_query_experiences__experience_id__executions_get"];
  };
  "/api/v1/admin/users": {
    "get": operations["list_users_api_v1_admin_users_get"];
    "post": operations["create_user_api_v1_admin_users_post"];
  };
  "/api/v1/admin/users/{user_id}": {
    "put": operations["update_user_api_v1_admin_users__user_id__put"];
    "delete": operations["delete_user_api_v1_admin_users__user_id__delete"];
  };
  "/api/v1/auth/change-password": {
    "post": operations["change_password_api_v1_auth_change_password_post"];
  };
  "/api/v1/auth/login": {
    "post": operations["login_api_v1_auth_login_post"];
  };
  "/api/v1/auth/logout": {
    "post": operations["logout_api_v1_auth_logout_post"];
  };
  "/api/v1/auth/me": {
    "get": operations["me_api_v1_auth_me_get"];
  };
  "/api/v1/auth/refresh": {
    "post": operations["refresh_api_v1_auth_refresh_post"];
  };
  "/api/v1/chat/attachment/delete": {
    "post": operations["api_delete_attachment_api_v1_chat_attachment_delete_post"];
  };
  "/api/v1/chat/attachment/get": {
    "get": operations["api_get_attachment_api_v1_chat_attachment_get_get"];
  };
  "/api/v1/chat/attachment/upload": {
    "post": operations["api_upload_attachment_api_v1_chat_attachment_upload_post"];
  };
  "/api/v1/chat/create": {
    "post": operations["api_create_conversation_api_v1_chat_create_post"];
  };
  "/api/v1/chat/delete": {
    "post": operations["api_delete_conversations_api_v1_chat_delete_post"];
  };
  "/api/v1/chat/draft/{conversation_id}": {
    "delete": operations["api_delete_draft_conversation_api_v1_chat_draft__conversation_id__delete"];
  };
  "/api/v1/chat/ls": {
    "get": operations["api_get_conversations_api_v1_chat_ls_get"];
  };
  "/api/v1/chat/ls/{conversation_id}": {
    "get": operations["api_get_messages_api_v1_chat_ls__conversation_id__get"];
  };
  "/api/v1/chat/stream": {
    "post": operations["api_stream_chat_api_v1_chat_stream_post"];
  };
  "/api/v1/chat/update": {
    "post": operations["api_update_conversation_api_v1_chat_update_post"];
  };
  "/api/v1/chat/{conversation_id}/events": {
    "get": operations["api_subscribe_conversation_run_api_v1_chat__conversation_id__events_get"];
  };
  "/api/v1/chat/{conversation_id}/resume": {
    "post": operations["api_resume_chat_api_v1_chat__conversation_id__resume_post"];
  };
  "/api/v1/chat/{conversation_id}/run": {
    "get": operations["api_get_conversation_run_status_api_v1_chat__conversation_id__run_get"];
  };
  "/api/v1/chat/{conversation_id}/stop": {
    "post": operations["api_stop_conversation_run_api_v1_chat__conversation_id__stop_post"];
  };
  "/api/v1/chat/{conversation_id}/subagents/{analysis_id}/{agent_type}/{session_id}/runs/{delegation_id}/messages": {
    "get": operations["api_get_subagent_messages_api_v1_chat__conversation_id__subagents__analysis_id___agent_type___session_id__runs__delegation_id__messages_get"];
  };
  "/api/v1/meta/columns/batch-delete": {
    "post": operations["delete_columns_api_v1_meta_columns_batch_delete_post"];
  };
  "/api/v1/meta/columns/sync": {
    "post": operations["sync_column_indexes_api_v1_meta_columns_sync_post"];
  };
  "/api/v1/meta/columns/sync-values": {
    "post": operations["sync_column_values_api_v1_meta_columns_sync_values_post"];
  };
  "/api/v1/meta/export": {
    "get": operations["export_metadata_api_v1_meta_export_get"];
  };
  "/api/v1/meta/import": {
    "post": operations["import_metadata_api_v1_meta_import_post"];
  };
  "/api/v1/meta/metrics": {
    "get": operations["list_metric_infos_api_v1_meta_metrics_get"];
  };
  "/api/v1/meta/metrics/batch-delete": {
    "post": operations["delete_metrics_api_v1_meta_metrics_batch_delete_post"];
  };
  "/api/v1/meta/metrics/sync": {
    "post": operations["sync_metric_indexes_api_v1_meta_metrics_sync_post"];
  };
  "/api/v1/meta/metrics/{metric_name}": {
    "put": operations["upsert_metric_info_api_v1_meta_metrics__metric_name__put"];
  };
  "/api/v1/meta/source-tables": {
    "get": operations["list_source_tables_api_v1_meta_source_tables_get"];
  };
  "/api/v1/meta/tables": {
    "get": operations["list_table_infos_api_v1_meta_tables_get"];
  };
  "/api/v1/meta/tables/batch-delete": {
    "post": operations["delete_tables_api_v1_meta_tables_batch_delete_post"];
  };
  "/api/v1/meta/tables/sync": {
    "post": operations["sync_table_indexes_api_v1_meta_tables_sync_post"];
  };
  "/api/v1/meta/tables/sync-values": {
    "post": operations["sync_table_values_api_v1_meta_tables_sync_values_post"];
  };
  "/api/v1/meta/tables/{t_name}": {
    "put": operations["upsert_table_info_api_v1_meta_tables__t_name__put"];
  };
  "/api/v1/meta/tables/{t_name}/columns": {
    "get": operations["list_column_infos_api_v1_meta_tables__t_name__columns_get"];
  };
  "/api/v1/meta/tables/{t_name}/columns/{c_name}": {
    "put": operations["upsert_column_info_api_v1_meta_tables__t_name__columns__c_name__put"];
  };
  "/api/v1/tasks/{task_id}": {
    "get": operations["get_task_status_api_v1_tasks__task_id__get"];
  };
}
